#!/usr/bin/env python3
"""
Phase 2: Translate all wo: "..." fields to Wolof (CLAD orthography)
Based on the Assimil "Guide de conversation Wolof" content.
"""
import json
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'output')

# ── Translations by lesson ──────────────────────────────────────────────

TRANSLATIONS = {
    # ── VILLE (11 cards) ──
    "ville_01": "Ci biir dëkk bi.",
    "ville_02": "ngir gis sa yoon.",
    "ville_03": "Fan laa man a gis wen, baal ma?",
    "ville_04": "Baal ma, fan la Mise bu jigéen bi nekk?",
    "ville_05": "Dem sa kanam ba ci rond-point bi.",
    "ville_06": "Miy làmmiñ wu njël wi ci càmmoñ.",
    "ville_07": "Dafa war nga dellu ci ginnaaw te wocc ci ndijoor ci stasiyoŋ esaas bi.",
    "ville_08": "Kaar bi.",
    "ville_09": "Fan la tëralug P9 bi nekk?",
    "ville_10": "Lan mooy kaar bi ñu dem ci...?",
    "ville_11": "Fan laa war a wàcc ngir...?",

    # ── MUSEES (13 cards) ──
    "musees_01": "Xool ekspozisiyoŋ, mise ak site turistik.",
    "musees_02": "Ndax man nañu xool...?",
    "musees_03": "Ndax am na wisit gide?",
    "musees_04": "Dama bëgg a jëf biye bu ekspozisiyoŋ bi.",
    "musees_05": "Ndax am na tarif wu wàññi ngir...?",
    "musees_06": "Xale yi.",
    "musees_07": "Yeneen kuriozite.",
    "musees_08": "Katedral bu Ndakaaru.",
    "musees_09": "Suuf su Lompul.",
    "musees_10": "Marse Sandaga.",
    "musees_11": "Monasteer bu Kër Musa.",
    "musees_12": "Pale presidaŋsiyel bi.",
    "musees_13": "Reseerw bu Bandiya.",

    # ── POSTE (2 cards) ──
    "poste_01": "Ci post bi.",
    "poste_02": "Dama bëgg a yónne koli bii.",

    # ── TELEPHONE (5 cards) ──
    "telephone_01": "Ci telefon bi.",
    "telephone_02": "Waaw, aloo?",
    "telephone_03": "Jàmm ak jàmm.",
    "telephone_04": "Kan moo ko yónne?",
    "telephone_05": "Adama la ko yónne.",

    # ── INTERNET (5 cards) ──
    "internet_01": "Enternet.",
    "internet_02": "Ndax am na aksee Enternet ci otel bi?",
    "internet_03": "Lan mooy kod bu wifi bi?",
    "internet_04": "Ndax xam nga fan la siber kafe am fii?",
    "internet_05": "Ndax man ngeen a print fisiye bii?",

    # ── ADMINISTRATION (22 cards) ──
    "administration_01": "Administrasiyoŋ bi.",
    "administration_02": "Dama di seet ambasaad bi.",
    "administration_03": "bu Belsik.",
    "administration_04": "bu Kanada.",
    "administration_05": "bu Faraas.",
    "administration_06": "bu Suwis.",
    "administration_07": "ci komisariya bi.",
    "administration_08": "Samay papye lañu réer.",
    "administration_09": "Ndax man ngeen a jox ma atestasiyoŋ proviswaar?",
    "administration_10": "Dañu ma racc sama saak.",
    "administration_11": "Dama bëgg a porter plaŋt.",
    "administration_12": "Dañu ma sàcc.",
    "administration_13": "Sama aparey foto.",
    "administration_14": "Xaalis bi ma amoon ci kaw ma.",
    "administration_15": "Sama kart kreedi.",
    "administration_16": "Samay seek du waayas!",
    "administration_17": "Samay caabi.",
    "administration_18": "Sama ordinatëer.",
    "administration_19": "Samay papye!",
    "administration_20": "Sama portaabal.",
    "administration_21": "Sama portëfëy.",
    "administration_22": "Sama oto.",

    # ── BANQUE (10 cards) ──
    "banque_01": "Ci baŋk bi.",
    "banque_02": "Fan laa man a gis?",
    "banque_03": "ab baŋk.",
    "banque_04": "Ab distribitëer otomatik.",
    "banque_05": "Dama bëgg a...",
    "banque_06": "soppi seek du waayas.",
    "banque_07": "ankeese ab seek.",
    "banque_08": "def ab depo ci ab koŋt.",
    "banque_09": "def ab wiremaa.",
    "banque_10": "Jël xaalis.",

    # ── SPECTACLES (2 cards) ──
    "spectacles_01": "Génne ci sinema, teyaatar ak koŋseer.",
    "spectacles_02": "Ñaata mooy priig bu biye bi?",

    # ── COIFFEUR (3 cards) ──
    "coiffeur_01": "Ci koyifëer bi.",
    "coiffeur_02": "Dama bëgg ñu rëdd ma kawar gi.",
    "coiffeur_03": "Ndax man ngeen a trase ma kawar gi?",

    # ── CAMPAGNE (22 cards) ──
    "campagne_01": "Ci wetu dëkk, ci plaaas bi, ci tund bi.",
    "campagne_02": "Spoor ak lwazir.",
    "campagne_03": "Lüt.",
    "campagne_04": "Sudoo.",
    "campagne_05": "Ràbb.",
    "campagne_06": "Ekitasiyoŋ.",
    "campagne_07": "Xarañ.",
    "campagne_08": "Peec!",
    "campagne_09": "Yëngël.",
    "campagne_10": "Kaad.",
    "campagne_11": "Dox.",
    "campagne_12": "Welo.",
    "campagne_13": "Danu bëgg a jàng njël wu njëkk ci lüt bi.",
    "campagne_14": "Ndax man nañu dox ak fas?",
    "campagne_15": "Ci pisin bi.",
    "campagne_16": "Ñaata mooy duggu ci pisin bi?",
    "campagne_17": "Ndax am na pisin ngir xale yi?",
    "campagne_18": "Lan mooy yoon wi ñu dem ci plaaas bi?",
    "campagne_19": "Dama di seet plaaas bu ñu seetlu.",
    "campagne_20": "Dama bëgg a lowe...",
    "campagne_21": "ab parasol.",
    "campagne_22": "Ab serwiyeet.",

    # ── CAMPING (9 cards) ──
    "camping_01": "Kamp ak kampiŋ.",
    "camping_02": "Ñaata mooy tarif bi ngir...?",
    "camping_03": "Ndax nege yi am nañu duus bu seen bopp?",
    "camping_04": "Ndax man nañu tëdd sunu tënt fii ngir guddi gii?",
    "camping_05": "Garab ak mbëy bu àll.",
    "camping_06": "Ndax dafa soxla otorizasiyoŋ ngir xool Park nasiyonal bu Ñokolo-Koba?",
    "camping_07": "Ndax man nga wax ma?",
    "camping_08": "Lu ñu tere ci park bi.",
    "camping_09": "Akasiya Albida.",

    # ── ANIMAUX (38 cards) ──
    "animaux_01": "Mala.",
    "animaux_02": "Mbaam-xuux.",
    "animaux_03": "Rab.",
    "animaux_04": "Teel.",
    "animaux_05": "Golo.",
    "animaux_06": "Njamala.",
    "animaux_07": "Jaan.",
    "animaux_08": "Jaar.",
    "animaux_09": "Gaseel.",
    "animaux_10": "Jibee.",
    "animaux_11": "Mbott.",
    "animaux_12": "Yéen.",
    "animaux_13": "Lëk.",
    "animaux_14": "Séq.",
    "animaux_15": "Lëwër.",
    "animaux_16": "Peedar.",
    "animaux_17": "Mbaam-àll.",
    "animaux_18": "Pisoŋ.",
    "animaux_19": "Jaalo.",
    "animaux_20": "Raat.",
    "animaux_21": "Jëdd.",
    "animaux_22": "Janax.",
    "animaux_23": "Jaan bu ñàkk.",
    "animaux_24": "Gunóor.",
    "animaux_25": "Yamb.",
    "animaux_26": "Jargoñ.",
    "animaux_27": "Kafar.",
    "animaux_28": "Sëf.",
    "animaux_29": "Jipp.",
    "animaux_30": "Wutt.",
    "animaux_31": "Yéeféef.",
    "animaux_32": "Sgorpiyoŋ.",
    "animaux_33": "Tiik.",
    "animaux_34": "Sgorpiyoŋ la ma topp.",
    "animaux_35": "Dama soxla aŋtiweneŋ ngir doom ju jaan.",
    "animaux_36": "Dama bëgg ab repilsif ngir yéeféef yi.",
    "animaux_37": "Ndax am ngeen mustikeer?",
    "animaux_38": "Dama am alersi.",

    # ── HEBERGEMENT (29 cards) ──
    "hebergement_01": "Toog.",
    "hebergement_02": "Rëzerwasiyoŋ otel.",
    "hebergement_03": "Dama soxla...",
    "hebergement_04": "ab nege ak lal bu ñaar.",
    "hebergement_05": "ab nege bu ñaari lal ak ab lal bu cosaan.",
    "hebergement_06": "Ñaar nañu mag ak ñaari xale.",
    "hebergement_07": "Danuy toog dale ci 10 ba 17 awril.",
    "hebergement_08": "War ngeen a bàyyi ab kosiyoŋ ci rëzerwasiyoŋ bi.",
    "hebergement_09": "Ndax priig bi ab ndeki la bokk?",
    "hebergement_10": "Ndax am na klimatizasiyoŋ ci nege yi?",
    "hebergement_11": "Ci resepsiyoŋ bi.",
    "hebergement_12": "Dama rëzerwe ab nege ci tur bu...",
    "hebergement_13": "Ñaata guddi?",
    "hebergement_14": "Ndax man ngeen a fenk ma ëllëg ci 6 waxtu?",
    "hebergement_15": "Ban waxtu lanu war a delloo caabi bi?",
    "hebergement_16": "Wokabileer bu serwis yi.",
    "hebergement_17": "Ndax am ngeen koŋsiñ bu bagaas?",
    "hebergement_18": "Ndax man ngeen a sàmm sunu bagaas ba tey ci ngoon?",
    "hebergement_19": "Ndax am na wifi ci nege yi?",
    "hebergement_20": "Ndax man ngeen a def ma...?",
    "hebergement_21": "ab kafe bu ñuul.",
    "hebergement_22": "Endika.",
    "hebergement_23": "Ab tartin jaamboŋ ak tamaate.",
    "hebergement_24": "Ab tartin ak bëer.",
    "hebergement_25": "Su am na ay ndaw yu ndaw.",
    "hebergement_26": "Robine bi di dagg.",
    "hebergement_27": "Ab ampul dafa ngi sori.",
    "hebergement_28": "Fay not bi.",
    "hebergement_29": "Man naa fay...",

    # ── RESTAURANT (17 cards) ──
    "restaurant_01": "Ci restoraa bi.",
    "restaurant_02": "Jàmm ak jàmm, dama rëzerwe ab taabël.",
    "restaurant_03": "Dama bëgg a rëzerwe ab taabël ngir tey ci ngoon.",
    "restaurant_04": "ngir 22 waxtu, ngir ñeenti nit ci tur bu Umar Gay.",
    "restaurant_05": "Ndax am ngeen ab taabël ngir juróom benni nit?",
    "restaurant_06": "Ndax rëzerwe ngeen?",
    "restaurant_07": "Ndax am ngeen ab menü?",
    "restaurant_08": "Tànnal ngeen?",
    "restaurant_09": "Soppi ngeen ko firi walla grill?",
    "restaurant_10": "Lan mooy garnitir bi?",
    "restaurant_11": "Ble.",
    "restaurant_12": "ab yeneen paka.",
    "restaurant_13": "Ab serwiyeet.",
    "restaurant_14": "mburu.",
    "restaurant_15": "Lan ngeen am ci galaas?",
    "restaurant_16": "Fan la wen yi nekk, baal ma?",
    "restaurant_17": "Spesiyalite ak pala tradisiyonel.",

    # ── METS (90 cards) ──
    "mets_01": "Wokabileer bu lekk ak prodwi.",
    "mets_02": "Buuseeri bi.",
    "mets_03": "Yaapa.",
    "mets_04": "Blaa.",
    "mets_05": "Nag.",
    "mets_06": "Koteleet bu mbaam-ëtt.",
    "mets_07": "Koteleet bu yàpp.",
    "mets_08": "Koteleet bu mbuus.",
    "mets_09": "Koseeleet.",
    "mets_10": "Daande.",
    "mets_11": "Epool.",
    "mets_12": "File bu nag.",
    "mets_13": "File bu mbaam.",
    "mets_14": "Pate.",
    "mets_15": "Xar.",
    "mets_16": "Ginaar.",
    "mets_17": "Stek.",
    "mets_18": "Keesiye.",
    "mets_19": "Yàpp bu tuur.",
    "mets_20": "Sarkiteri bi.",
    "mets_21": "Serwell.",
    "mets_22": "Xol.",
    "mets_23": "Res.",
    "mets_24": "Jaamboŋ.",
    "mets_25": "Làmmiñ.",
    "mets_26": "Roñoŋ.",
    "mets_27": "Sosis.",
    "mets_28": "Sosisoŋ.",
    "mets_29": "Ay tëral bu jaamboŋ.",
    "mets_30": "Ay tëral bu sosisoŋ.",
    "mets_31": "Posoŋëri bi.",
    "mets_32": "Jox ma ñetti darne bu mëru.",
    "mets_33": "Ndax man ngeen a ubbi doraad bii?",
    "mets_34": "Karp.",
    "mets_35": "Sannjar.",
    "mets_36": "Ekrewis.",
    "mets_37": "Doraad.",
    "mets_38": "Gumbaas.",
    "mets_39": "Omaar.",
    "mets_40": "Laŋgust.",
    "mets_41": "Mile.",
    "mets_42": "Sardin.",
    "mets_43": "Sees.",
    "mets_44": "Sol.",
    "mets_45": "Toŋ.",
    "mets_46": "Meññefu ak legim.",
    "mets_47": "Aay.",
    "mets_48": "Anana.",
    "mets_49": "Obersin.",
    "mets_50": "Awokaa.",
    "mets_51": "Banaana.",
    "mets_52": "Karoot.",
    "mets_53": "Sitroŋ.",
    "mets_54": "Koŋkoŋbër.",
    "mets_55": "Kurseet.",
    "mets_56": "Su fler.",
    "mets_57": "Arikoo weer, arikoo weex.",
    "mets_58": "Laŋti.",
    "mets_59": "Mañog.",
    "mets_60": "Meloŋ.",
    "mets_61": "Nawet.",
    "mets_62": "Kokko.",
    "mets_63": "Soble.",
    "mets_64": "Oliw.",
    "mets_65": "Oraans.",
    "mets_66": "Paŋpëlumus.",
    "mets_67": "Pasteg.",
    "mets_68": "Persil.",
    "mets_69": "Peti pwa.",
    "mets_70": "Pimaa.",
    "mets_71": "Pwaaro.",
    "mets_72": "Pwawroŋ.",
    "mets_73": "Pombiteer.",
    "mets_74": "Pom.",
    "mets_75": "Reeseŋ.",
    "mets_76": "Tamaate.",
    "mets_77": "Fasoŋ bu preparasiyoŋ ak soos.",
    "mets_78": "Preparasiyoŋ bu pala yi.",
    "mets_79": "Yassa.",
    "mets_80": "Tiyëbujen.",
    "mets_81": "Laax.",
    "mets_82": "Musel.",
    "mets_83": "Mafe.",
    "mets_84": "Tufe.",
    "mets_85": "Baxal.",
    "mets_86": "Firi.",
    "mets_87": "Sele.",
    "mets_88": "Marine.",
    "mets_89": "Roti.",
    "mets_90": "Breze.",

    # ── ALCOOL (9 cards) ──
    "alcool_01": "Sangara.",
    "alcool_02": "Lan ngeen bëgg a naan?",
    "alcool_03": "Ndax am ngeen kart bu biñ?",
    "alcool_04": "Ndax man ngeen a indil ma?",
    "alcool_05": "Ab weer bu...",
    "alcool_06": "Ab demi buteey bu...",
    "alcool_07": "Ab buteey bu...",
    "alcool_08": "Ab biyer.",
    "alcool_09": "Dinaa lekk jën.",

    # ── BOISSONS (12 cards) ──
    "boissons_01": "Yeneen naan.",
    "boissons_02": "Dinaa jël...",
    "boissons_03": "ab kafe.",
    "boissons_04": "Ab kafe ak meew.",
    "boissons_05": "Ab kafe bu sedd.",
    "boissons_06": "Ab sokola.",
    "boissons_07": "Ab ndox mineral.",
    "boissons_08": "Ab ate plaa.",
    "boissons_09": "Ab jis bu meññefu.",
    "boissons_10": "Ataya.",
    "boissons_11": "Ndax man ngeen a indil nu ab karaf bu ndox?",
    "boissons_12": "Dama bëgg ab kafe.",

    # ── MAGASINS (19 cards) ──
    "magasins_01": "Magaseŋ ak serwis.",
    "magasins_02": "Dama di seet...",
    "magasins_03": "ab fleriste.",
    "magasins_04": "Dafa jafe tuuti.",
    "magasins_05": "Def ma ab kilo.",
    "magasins_06": "Junni ak juróom téeméer dërëm CFA la.",
    "magasins_07": "Téere, rewi, surnal, misik.",
    "magasins_08": "Ab kiosk bu surnal ci wet fii.",
    "magasins_09": "Ab libreeri fii.",
    "magasins_10": "Ndax am ngeen...?",
    "magasins_11": "Ay surnal ci faraase.",
    "magasins_12": "Ndax am ngeen ay téere ci aada yi?",
    "magasins_13": "Dama bëgg a jënd albóm bu artis bii.",
    "magasins_14": "Ndax am ngeen ab artis ñu ma digle?",
    "magasins_15": "Blanseeri, tentiree.",
    "magasins_16": "Aamme ngeen?",
    "magasins_17": "Dama leen di bàyyi yii yëre.",
    "magasins_18": "Kañ lañuy pare?",
    "magasins_19": "Dañu set.",

    # ── VETEMENTS (5 cards) ──
    "vetements_01": "Yëre ak dàll.",
    "vetements_02": "Fan la kabin deseyaas yi nekk?",
    "vetements_03": "Masam.",
    "vetements_04": "Dafa ma tëj.",
    "vetements_05": "Dafa ma baax.",

    # ── TABAC (9 cards) ──
    "tabac_01": "Biro bu tabaa.",
    "tabac_02": "Dama bëgg...",
    "tabac_03": "ab pake bu sigareet.",
    "tabac_04": "ab kartus bu...",
    "tabac_05": "Ab buwaat bu alimeet.",
    "tabac_06": "Ab brike.",
    "tabac_07": "tabaa bu roole.",
    "tabac_08": "Ay fëy bu tabaa bu roole.",
    "tabac_09": "Ab reesaars ngir sigareet elektronik.",

    # ── PHOTO (9 cards) ──
    "photo_01": "Foto.",
    "photo_02": "Kart memwaar.",
    "photo_03": "Saarsëer.",
    "photo_04": "Dama bëgg a print ay foto.",
    "photo_05": "Sama aparey dafa baaxul.",
    "photo_06": "Ndax man ngeen a jël nu foto, baal ma?",
    "photo_07": "Ndax man naa la jël ab foto?",
    "photo_08": "Am na solo ngir jël ay foto fii.",
    "photo_09": "Man ngeen a jël ay foto ak flaas.",

    # ── PROVISIONS (36 cards) ──
    "provisions_01": "Prowizyoŋ.",
    "provisions_02": "Alimantasiyoŋ.",
    "provisions_03": "Bëer.",
    "provisions_04": "Bisko.",
    "provisions_05": "Bonboŋ.",
    "provisions_06": "Koŋfitir.",
    "provisions_07": "Farin.",
    "provisions_08": "Galaas.",
    "provisions_09": "Wil.",
    "provisions_10": "Meew.",
    "provisions_11": "Mutaard.",
    "provisions_12": "Ëf.",
    "provisions_13": "Oliw.",
    "provisions_14": "Paa.",
    "provisions_15": "Pate.",
    "provisions_16": "Puwaar.",
    "provisions_17": "Ceeb.",
    "provisions_18": "Saandwis.",
    "provisions_19": "Xorom.",
    "provisions_20": "Sukër.",
    "provisions_21": "Biñ.",
    "provisions_22": "Winegër.",
    "provisions_23": "Isiyen ak swaŋ.",
    "provisions_24": "Bros bu bëñ.",
    "provisions_25": "Kus ngir doom ju ndaw.",
    "provisions_26": "Daŋtifris.",
    "provisions_27": "Deyodoraa.",
    "provisions_28": "Laam bu rasuwaar.",
    "provisions_29": "Maskara.",
    "provisions_30": "Muswaar bu kaayu.",
    "provisions_31": "Papye tuwalet.",
    "provisions_32": "Parfëŋ.",
    "provisions_33": "Peeñ.",
    "provisions_34": "Ruj a leewër.",
    "provisions_35": "Sawoŋ.",
    "provisions_36": "Saŋpuwaŋ.",

    # ── SOUVENIRS (10 cards) ──
    "souvenirs_01": "Xéwël.",
    "souvenirs_02": "Dama bëgg a yóbbu ab xéwël bu Senegaal ngir ay xarit.",
    "souvenirs_03": "Dama bëgg a jënd ab mask afrikeŋ.",
    "souvenirs_04": "Ndax man naa xool bisu yi?",
    "souvenirs_05": "Dinaa jël...",
    "souvenirs_06": "Bërse bii.",
    "souvenirs_07": "Kuliyee bii.",
    "souvenirs_08": "Ak koŋtoŋ bii.",
    "souvenirs_09": "Ñaata la?",
    "souvenirs_10": "Kaado la. Ndax man nga ko buulte ma?",

    # ── RDV-PRO (7 cards) ──
    "rdv-pro_01": "Rande-wu profesiyonel.",
    "rdv-pro_02": "Ndax man ngeen a jox ma ab rande-wu ak Maam Jóob?",
    "rdv-pro_03": "Aarba ci juróom waxtu.",
    "rdv-pro_04": "Baax na, nu defal noonu.",
    "rdv-pro_05": "Xool àntëpriis bi.",
    "rdv-pro_06": "Aatële bi.",
    "rdv-pro_07": "Dama leen di bàyyi sama kart du wizit.",

    # ── SANTE (23 cards) ──
    "sante_01": "Wer gu yaram.",
    "sante_02": "Ci doktëer bi.",
    "sante_03": "Dama soxla a dem ci irsaŋs.",
    "sante_04": "Dama baaxul.",
    "sante_05": "Dama feebar.",
    "sante_06": "Kañ mooy man a gis ma?",
    "sante_07": "Seŋtoom.",
    "sante_08": "Dama am ay frisoŋ.",
    "sante_09": "Sama biir dafa ñor.",
    "sante_10": "Dama am ay rusëer.",
    "sante_11": "Dafa ma yàqu.",
    "sante_12": "Dafa ma metti su ma yengee loxo bi.",
    "sante_13": "Dafa ma metti su ma doxe.",
    "sante_14": "Dama gëm ne dama am ipertaŋsiyoŋ.",
    "sante_15": "Dama gëm ne sama taŋsiyoŋ dafa wàññi.",
    "sante_16": "Metit ak boppam bu yaram.",
    "sante_17": "ci artikilasiyoŋ yi.",
    "sante_18": "Dama dacc.",
    "sante_19": "Bakkan bi.",
    "sante_20": "Wer gu yaram bu jigéen.",
    "sante_21": "Dama am ñaari weeru ñàkk.",
    "sante_22": "Dama ëmb.",
    "sante_23": "Dama soxla a def ab ekografi.",

    # ── LECON51 (19 cards) ──
    "lecon51_01": "Ci doktëer bi.",
    "lecon51_02": "Dinaa la dëglu.",
    "lecon51_03": "Dafa war ñu def...",
    "lecon51_04": "ay egzameŋ.",
    "lecon51_05": "Dinaa la yónne ci ab spesiyalist.",
    "lecon51_06": "Dinga war a...",
    "lecon51_07": "Dafa war ñu piké la.",
    "lecon51_08": "Ndax am na medikamaa bu la am alersi?",
    "lecon51_09": "Ci daŋtist bi.",
    "lecon51_10": "Dama am ab apse.",
    "lecon51_11": "Dinaa war a rax la ab bëñ.",
    "lecon51_12": "Ndax man nga ubbi sa gémmiñ?",
    "lecon51_13": "Tuufu.",
    "lecon51_14": "Ci oftalmolog bi.",
    "lecon51_15": "Dama dagg ab weer.",
    "lecon51_16": "Am na dara ci sama bët, dafa ma metti.",
    "lecon51_17": "Ndax man ngeen a...",
    "lecon51_18": "Won ma ay moŋtir?",
    "lecon51_19": "Dama bëgg ay linet bu jëmm ak ab baax proteksiyoŋ.",

    # ── LECON52 (10 cards) ──
    "lecon52_01": "Ci farmaasi bi.",
    "lecon52_02": "Ndax man ngeen a won ma ab farmaasi?",
    "lecon52_03": "Dama am ab ordanaas.",
    "lecon52_04": "Ndax man naa jël medikamaa bii te amul ordanaas?",
    "lecon52_05": "Ndax man naa jël medikamaa yii àddina?",
    "lecon52_06": "Ndax man ngeen a jox ma dara ngir...?",
    "lecon52_07": "Ay dàkk...",
    "lecon52_08": "Ab kotoŋ.",
    "lecon52_09": "Dara ngir tàngu.",
    "lecon52_10": "Paŋsmaa.",
}

def main():
    new_lessons = [
        'ville','musees','poste','telephone','internet','administration','banque',
        'spectacles','coiffeur','campagne','camping','animaux','hebergement',
        'restaurant','mets','alcool','boissons','magasins','vetements','tabac',
        'photo','provisions','souvenirs','rdv-pro','sante','lecon51','lecon52'
    ]

    total_translated = 0
    total_cards = 0

    for lid in new_lessons:
        fpath = os.path.join(OUTPUT_DIR, f'lesson_{lid}.json')
        with open(fpath, 'r') as f:
            data = json.load(f)

        translated = 0
        for card in data['cards']:
            cid = card['id']
            if cid in TRANSLATIONS:
                card['wo'] = TRANSLATIONS[cid]
                translated += 1
            elif card['wo'] == '...':
                print(f"  WARNING: No translation for {cid}: {card['fr']}")

        total_translated += translated
        total_cards += len(data['cards'])

        with open(fpath, 'w') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"  {lid}: {translated}/{len(data['cards'])} translated")

    print(f"\nTotal: {total_translated}/{total_cards} cards translated")

if __name__ == '__main__':
    main()
